export enum BoardState {
    IDLE = 'IDLE',
    INITIALIZING = 'INITIALIZING',
    UPDATING = 'UPDATING',
    FETCHING = 'FETCHING',
    ERROR = 'ERROR',
}

export enum BoardUpdatingState {
    ADDING_COLUMN = 'ADDING_COLUMN',
    UPDATING_COLUMN = 'UPDATING_COLUMN',
    DELETING_COLUMN = 'DELETING_COLUMN',
    ADDING_ISSUE = 'ADDING_ISSUE',
    UPDATING_ISSUE = 'UPDATING_ISSUE',
    DELETING_ISSUE = 'DELETING_ISSUE',
    UPDATING = 'UPDATING',
}

export enum BoardEvents {
    FETCH = 'FETCH',
    GO_TO_IDLE = 'GO_TO_IDLE',
    ADD_COLUMN = 'ADD_COLUMN',
    UPDATE_COLUMN = 'ADD_COLUMN',
    DELETE_COLUMN = 'DELETE_COLUMN',
    ADD_ISSUE = 'ADD_ISSUE',
    UPDATE_ISSUE = 'UPDATE_ISSUE',
    DELETE_ISSUE = 'DELETE_ISSUE',
    DELETE = 'DELETE',
    UPDATE = 'UPDATE',
}
